import Head from "next/head";

const HeadZone = () => {
  return (
    <>
      <Head>
        <title>競プロトレーニング</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          href="/images/task_tracker_icon.png"
        />
      </Head>
    </>
  );
};

export default HeadZone;
